name: ribotools
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - rpbp>=4.0.0
  - htseq
  - r-base=4.4.3
  - bioconductor-ihw
  - bioconductor-apeglm
  - bioconductor-deseq2
  - r-argparser
  - r-ashr
  - r-devtools
  - r-openxlsx
  - r-r.utils
  - r-tidyverse
  - r-yaml
